name: 'Aliyun OSS Auto Upload'
description: 'Provide a description here'
author: 'tiyee'
inputs:
  region:
    required: true
    description: the bucket data region location
  access-key-id:
    required: true
    description: access key
  access-key-secret:
    required: true
    description: access secret
  bucket:
    required: true
    description: bucket
  secure:
    required: true
    description: access secret
    default: 'true'
  entry:
    required: true
    description: entry
    default: dist/**/*
  remote-dir:
    required: true
    description: remote-dir
    default: /
  path-rewrite:
    required: true
    description: path-rewrite
    default: ^dist/
runs:
  using: node12
  main: dist/index.js
branding:
  icon: upload-cloud  
  color: red
